### 목표
 - sklearn 사용법 숙지
 - 집의 특징 데이터를 학습해서 집 가격을 예측해보자
 - 올바른 모델 평가방법을 알아보자

### 모델정의

In [18]:
from sklearn.tree import DecisionTreeRegressor

In [19]:
house_model = DecisionTreeRegressor(random_state=203)

In [2]:
import pandas as pd

In [8]:
house_data = pd.read_csv("melb_data.csv")


In [9]:
#데이터프레임의 정보를 요약해서 볼 수 있는 함수
house_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Suburb         13580 non-null  object 
 1   Address        13580 non-null  object 
 2   Rooms          13580 non-null  int64  
 3   Type           13580 non-null  object 
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object 
 6   SellerG        13580 non-null  object 
 7   Date           13580 non-null  object 
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object 
 17  Lattitude      13580 non-null  float64
 18  Longti

In [11]:
house_data

Suburb           Address  Rooms Type      Price Method  \
0         Abbotsford      85 Turner St      2    h  1480000.0      S   
1         Abbotsford   25 Bloomburg St      2    h  1035000.0      S   
2         Abbotsford      5 Charles St      3    h  1465000.0     SP   
3         Abbotsford  40 Federation La      3    h   850000.0     PI   
4         Abbotsford       55a Park St      4    h  1600000.0     VB   
...              ...               ...    ...  ...        ...    ...   
13575  Wheelers Hill      12 Strada Cr      4    h  1245000.0      S   
13576   Williamstown     77 Merrett Dr      3    h  1031000.0     SP   
13577   Williamstown       83 Power St      3    h  1170000.0      S   
13578   Williamstown      96 Verdon St      4    h  2500000.0     PI   
13579     Yarraville        6 Agnes St      4    h  1285000.0     SP   

        SellerG        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  \
0        Biggin   3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0   
1        Biggin   4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0   
2        Biggin   4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0   
3        Biggin   4/03/2017       2.5    3067.0  ...       2.0  1.0      94.0   
4        Nelson   4/06/2016       2.5    3067.0  ...       1.0  2.0     120.0   
...         ...         ...       ...       ...  ...       ...  ...       ...   
13575     Barry  26/08/2017      16.7    3150.0  ...       2.0  2.0     652.0   
13576  Williams  26/08/2017       6.8    3016.0  ...       2.0  2.0     333.0   
13577     Raine  26/08/2017       6.8    3016.0  ...       2.0  4.0     436.0   
13578   Sweeney  26/08/2017       6.8    3016.0  ...       1.0  5.0     866.0   
13579   Village  26/08/2017       6.3    3013.0  ...       1.0  1.0     362.0   

       BuildingArea  YearBuilt  CouncilArea Lattitude  Longtitude  \
0               NaN        NaN        Yarra -37.79960   144.99840   
1              79.0     1900.0        Yarra -37.80790   144.99340   
2             150.0     1900.0        Yarra -37.80930   144.99440   
3               NaN        NaN        Yarra -37.79690   144.99690   
4             142.0     2014.0        Yarra -37.80720   144.99410   
...             ...        ...          ...       ...         ...   
13575           NaN     1981.0          NaN -37.90562   145.16761   
13576         133.0     1995.0          NaN -37.85927   144.87904   
13577           NaN     1997.0          NaN -37.85274   144.88738   
13578         157.0     1920.0          NaN -37.85908   144.89299   
13579         112.0     1920.0          NaN -37.81188   144.88449   

                       Regionname Propertycount  
0           Northern Metropolitan        4019.0  
1           Northern Metropolitan        4019.0  
2           Northern Metropolitan        4019.0  
3           Northern Metropolitan        4019.0  
4           Northern Metropolitan        4019.0  
...                           ...           ...  
13575  South-Eastern Metropolitan        7392.0  
13576        Western Metropolitan        6380.0  
13577        Western Metropolitan        6380.0  
13578        Western Metropolitan        6380.0  
13579        Western Metropolitan        6543.0  

[13580 rows x 21 columns]

In [ ]:
# 문제 : Rooms , Bathrooms, Landsize, Lattitude, Longtitude
# 답 : Price

In [12]:
x = house_data[['Rooms','Bathroom','Landsize', 'Lattitude', 'Longtitude']]
y = house_data['Price']

In [13]:
x

Rooms  Bathroom  Landsize  Lattitude  Longtitude
0          2       1.0     202.0  -37.79960   144.99840
1          2       1.0     156.0  -37.80790   144.99340
2          3       2.0     134.0  -37.80930   144.99440
3          3       2.0      94.0  -37.79690   144.99690
4          4       1.0     120.0  -37.80720   144.99410
...      ...       ...       ...        ...         ...
13575      4       2.0     652.0  -37.90562   145.16761
13576      3       2.0     333.0  -37.85927   144.87904
13577      3       2.0     436.0  -37.85274   144.88738
13578      4       1.0     866.0  -37.85908   144.89299
13579      4       1.0     362.0  -37.81188   144.88449

[13580 rows x 5 columns]

In [14]:
y

0        1480000.0
1        1035000.0
2        1465000.0
3         850000.0
4        1600000.0
           ...    
13575    1245000.0
13576    1031000.0
13577    1170000.0
13578    2500000.0
13579    1285000.0
Name: Price, Length: 13580, dtype: float64

In [15]:
x.shape, y.shape

((13580, 5), (13580,))

# 기술통계

In [16]:
x.describe()

Rooms      Bathroom       Landsize     Lattitude    Longtitude
count  13580.000000  13580.000000   13580.000000  13580.000000  13580.000000
mean       2.937997      1.534242     558.416127    -37.809203    144.995216
std        0.955748      0.691712    3990.669241      0.079260      0.103916
min        1.000000      0.000000       0.000000    -38.182550    144.431810
25%        2.000000      1.000000     177.000000    -37.856822    144.929600
50%        3.000000      1.000000     440.000000    -37.802355    145.000100
75%        3.000000      2.000000     651.000000    -37.756400    145.058305
max       10.000000      8.000000  433014.000000    -37.408530    145.526350

In [17]:
y.describe()

count    1.358000e+04
mean     1.075684e+06
std      6.393107e+05
min      8.500000e+04
25%      6.500000e+05
50%      9.030000e+05
75%      1.330000e+06
max      9.000000e+06
Name: Price, dtype: float64

In [20]:
house_model.fit(x,y)

DecisionTreeRegressor(random_state=203)

In [ ]:
# 종류가 정해져 있는 것 >> 범주형 데이터
# 개개인이 다 개인의 값을 갖는 것은 >> 수치형 데이터

### 예측

In [22]:
x_samples = x.iloc[:5000, :]   #data.iloc[행,열]   >> 행, 열 자를때 쓰는 
y_samples = y.iloc[:5000]

In [24]:
pre = house_model.predict(x_samples)
pre

array([1480000., 1035000., 1465000., ...,  790000., 1000000.,  860000.])

### 평가
 - 수치형 데이터는 오차 기반의 평가를 사용
 - 평균절대값오차(Mean Absolute Error)

In [25]:
from sklearn.metrics import mean_absolute_error

In [26]:
mean_absolute_error(y_samples, pre) #오차 1380

1380.7166666666667

In [30]:
house_model.predict([[5,3,558,-37.809203,144.995216]])

array([3001000.])

### 올바른 평가를 위해 훈련, 평가 데이터 나누기

In [31]:
from sklearn.model_selection import train_test_split #랜덤 샘플링

In [65]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=203)   #문제와 답을 7:3으로 쪼개 준다

In [66]:
# 훈련용 문제, 평가용 문제, 훈련용 정답, 평가용 정답

In [67]:
x_train.shape, y_train.shape

((10185, 5), (10185,))

In [68]:
x_test.shape,  y_test.shape

((3395, 5), (3395,))

In [69]:
# 학습
house_model.fit(x_train,y_train)

DecisionTreeRegressor(random_state=203)

In [70]:
# 예측
pre = house_model.predict(x_test)
pre

array([ 445000.,  410000.,  472000., ...,  360500., 1060000., 2850000.])

In [72]:
# 평가(평균, 절대값, 오차)
mean_absolute_error(y_test, pre)  #오차 24만

247448.44177712323